README.md, app/views/layouts/_ga.html.haml, config/application.rb
- Put a sample into your local .env file:
GA_TRACKING_ID=UA-XXXXX-X
- Render the _ga.html.haml file in the footer of your application as:
`= render 'layouts/ga'`
=> Enable google analytics

app/controllers/home_controller.rb, config/routes.rb, spec/features/person_browsing_spec.rb
- This will be the default point of entry for
a workspace user when they go to their peoplefinder
profile page
=> Implement my/profile path

manifest.yml
Adding peoplefinder worker in dev env
=> Update: manifest.yml

manifest.yml
Updates: 
- Added helth-check-type to process
- Added manifest for peoplefinder-worker for staging and production enviornment
=> Fix gds deploy

app/assets/stylesheets/digital-workspace-overrides/util/_links.scss, app/views/widgets/_nav.html.haml
couple of small responsive things and a navigation link
=> Responsive bugs

app/controllers/people_controller.rb, app/models/person.rb, app/models/report.rb, app/services/person_search.rb, app/views/people/_form.html.haml, app/views/people/_profile.html.haml, app/views/search/_person.html.haml, config/locales/en.yml, db/migrate/20171122114825_add_secondary_phone_country_code_to_people.rb, db/schema.rb, public/500.html, spec/models/person_spec.rb, spec/models/report_spec.rb, spec/services/person_search_spec.rb, spec/support/profile.rb
Here we have:
- enabled Landline and Mobile numbers
- fixed the 500 error page html title
- fixed the Country name on the profile page
- updated the Location in building form label
- implemented searching by Learning and Development Interests
=> Updates to the Profile and Form 

app/models/concerns/completion.rb, spec/factories.rb, spec/models/concerns/bucketed_completion_spec.rb, spec/models/concerns/completion_spec.rb, spec/models/group_spec.rb
- "location in building" is no longer a mandatory field, so we don't
include that in the completeness score
=> Refine the Completeness Score

app/views/layouts/_footer.html.haml
Brings footer links in line with those on Digital Workspace.
=> Update footer links

config/initializers/elasticsearch.rb
We are migrating Elasticsearch to GOV.UK PaaS (currently it runs
standalone on AWS). If a `VCAP_SERVICES` env variable is present,
we should get our ES URL from there.
=> Use `VCAP_SERVICES` env variable for ES if available

app/controllers/admin/profile_extracts_controller.rb
Add additional fields as requested by tech to CSV export functionality.
=> Expand range of fields in CSV extract

app/views/shared/_loginout.html.haml
As on Digital Workspace, this should say "view" rather than "edit".
=> Update "view profile" link copy

lib/tasks/peoplefinder/data.rake
- Add Staff SSO ID to seeded users
- Make seed data DIT-specific, not MoJ
=> Improve seed data

.rubocop_todo.yml, app/models/person.rb, app/services/person_search.rb, spec/models/person_spec.rb, spec/services/person_search_spec.rb
- Index phone number variations (with and without country code and
leading zero)
- Normalise search term if it looks like a phone number
=> Allow searching for people by phone number

.circleci/config.yml, .circleci/env
Switch `uktrade/peoplefinder` over to CircleCI to be in line with the rest of DIT.
=> Migrate from Travis to CircleCI

config/locales/en.yml
- Rename "shadowing" to "work shadowing"
- Add "International trade profession" to professions
=> Add additional fields to profiles

app/assets/stylesheets/digital-workspace-overrides/application.scss, app/assets/stylesheets/digital-workspace-overrides/components/_group-tree.scss, app/views/groups/_teams_in_team.html.haml, app/views/groups/_tree_level.html.erb, app/views/groups/tree.html.erb
- Add basic styling to the tree view for groups
- Add a link to the tree view to the groups show page
=> Add link to tree view in groups; basic styling

app/assets/stylesheets/digital-workspace-overrides/components/_group-tree.scss, app/views/groups/_teams_in_team.html.haml, app/views/groups/_tree_level.html.erb, app/views/groups/tree.html.erb
- Rename UI name for feature to "View all subteams"
- Make line spacing bigger to make it look less cramped
- Fix tabs -> spaces in SCSS
=> Copy and design tweaks for new tree view

config/application.rb, config/initializers/carrierwave.rb
- Rename `Rails.configuration.x.s3.key` to `access_key` as it conflicts
with `Hash#key`
- Change `eager_load_paths` back to `autoload_paths` pending further
investigation
=> Fix deploy failing on asset compilation

lib/vcap_services.rb, spec/lib/vcap_services_spec.rb
... instead of silently failing.
=> Raise when services are missing in VCAP_SERVICES

app/controllers/admin/management_controller.rb, app/views/admin/management/show.html.haml, config/initializers/sidekiq.rb
- Log Sidekiq logs in JSON
- Add basic stats to management page
=> Sidekiq tweaks

.reek.yml, db/migrate/20200214143000_remove_sessions.rb, db/schema.rb
Not needed anymore now that we are successfully using Redis for session
storage.
=> Remove sessions table from database

.reek.yml, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, config/environments/production.rb
- Add and set up `lograge` gem for improved logging, including SSO user
ID
- Remove `rails_12factor` gem (everything this does can be achieved in
simple configuration)
- Remove `logstasher` gem (we never used this at DIT, logs should just
go to STDOUT)
=> Improve logging and remove `rails_12factor`

app/views/people/_form.html.haml, config/locales/en.yml, spec/features/person_maintenance_spec.rb
We need to completely overhaul this awful form at some point. For now,
this at least makes it obvious which fields are mandatory.
=> Profile edit form tweaks

app/controllers/groups_controller.rb, app/views/groups/_form.html.haml, app/views/groups/show.html.erb
- Remove adding yourself to new group by default
- Fix issue with versions template check still accessing ivar
- Remove pointless `@editing_mode` ivar
=> Fix minor issues with GroupsController

app/views/people/_profile.html.haml, spec/support/profile.rb
This was different between edit form and profile show view.
=> Improve copy around phone numbers

app/views/people/_form.html.haml, app/views/people/_profile.html.haml, config/locales/legacy.en.yml
- Change "building I work in" to "place(s) I usually work"
- Add remote/home working option
=> Improve work location field

app/models/person.rb, app/views/people/_profile_field.html.slim, app/views/people/show.html.slim, app/webpacker/stylesheets/components/profile.scss
- Paginate 40 people per page (instead of 25) to avoid overhang
- Better text for person's own profile deletion request button
- Fix margin on "previous positions held" on profile
=> Various small UI fixes

app/services/person_search.rb
Also include profile photos which is another n+1 query on the
search results page.
=> Fix another n+1 query on search results

.rspec_parallel, Gemfile, Gemfile.lock, app/models/concerns/searchable.rb, bin/rails, bin/rake, bin/spring, config/database.yml, spec/models/person_spec.rb
- Add Spring to application
- Add `parallel_tests` support
=> Development improvements

.env.example, app/serializers/person_profile_serializer.rb, spec/serializers/person_profile_serializer_spec.rb
- Add new expected env keys to example
- Add two missing fields to profile API
=> Minor API tweaks

app/controllers/api/v2/data_workspace_exports_controller.rb, app/serializers/person_data_workspace_serializer.rb, spec/serializers/person_data_workspace_serializer_spec.rb
This adds a number of extra fields to the Data Workspace API and clears
up the naming of some existing fields.
=> Add additional fields to Data Workspace API

app/decorators/mailing_list_person_decorator.rb, spec/decorators/mailing_list_person_decorator_spec.rb
This will allow for more granular targeting of email campaigns.
=> Add country to mailing list merge fields

app/form_builders/people_finder_form_builder.rb, app/views/groups/_team_browser.html.slim, app/views/groups/_team_browser_node.html.slim, app/webpacker/javascript/controllers/team_browser_controller.js, app/webpacker/stylesheets/components/team_browser.scss, config/locales/en.yml
This adds custom keyboard handling to the people/groups team browser
=> Improve keyboard navigation in team browser

app/serializers/person_data_workspace_serializer.rb, spec/serializers/person_data_workspace_serializer_spec.rb
- Remove Skype name field
- Add contact email field
=> Update fields for Data Workspace export API

app/views/person_deletion_request/new.html.slim
This form submits remotely and doesn't redirect - it should be local.
=> Fix deletion requests not submitting properly

app/views/search/_person.html.slim
Fix the display of a person's name in search results.
=> Fix name display issue

config/locales/en.yml
Deployment steps:
1. merge and deploy code
2. run the following sql
```sql
UPDATE
people
SET
networks = array_replace(networks, 'age', 'generation');
UPDATE
people
SET
networks = array_replace(networks, 'women', 'gender');
UPDATE
people
SET
networks = array_replace(networks, 'lgbti_plus', 'lgbt_plus');
```
There will be a small window between deploying the code and running the SQL where the website will show missing translation errors to users.
=> PFM-58 Update "People Network" names.
