- .env
- .env.example
- Gemfile
- Gemfile.lock
- README.md
- app/controllers/problem_reports_controller.rb
- app/views/sessions/_login_page.html.haml
- config/application.rb
- config/initializers/omniauth.rb
- config/locales/en.yml
- lib/ditsso_internal.rb
- spec/controllers/person_email_controller_spec.rb
- spec/controllers/sessions_controller_spec.rb
- spec/features/login_page_spec.rb
- spec/features/omni_auth_authentication_spec.rb
- spec/support/login.rb
- spec/support/pages/person_confirm.rb
- spec/support/token_auth_enabler.rb
This PR replaces the google omniauth provider with the DIT's SSO provider.
Not to be merged into until we have an environment that allows multiple users to authenticated against the live provider.
> DIT SSO Implementation

- app/models/email_address.rb
- config/application.rb
- config/environments/test.rb
- spec/models/email_address_spec.rb
- Here we disable the permitted_domains feature
as we don’t know what domains the DIT users will
come from.
> Allow users from any domain to have an account

- .env.example
- README.md
- lib/ditsso_internal.rb
-  due to Cloudfoundry's routing we can't use the 
omniauth helpers to build the callback URL.
> Explicitly declare the SSO Callback URL

- README.md
- lib/ditsso_internal.rb
Here we revert the workarounds that were implemented due to the behaviour of URL forwarding in the production environment.
> Tidy up oauth

- app/controllers/concerns/session_person_creator.rb
- app/models/person.rb
- spec/features/omni_auth_authentication_spec.rb
- spec/services/person_search_spec.rb
- We need to establish the format of the auth
hash returned by the SSO. This has changed in
the test accounts
> Workaround for inconsistent SSO auth hash

- lib/tasks/_jasmine.rake
Here we disable jasmine as running `rake jasmine:ci` is blowing up the CI. We could restore this later but there are only 9 legacy tests so it is unlikely that will happen.
> Try to get travis working by disabling jasmine

- app/controllers/api/people_controller.rb
- app/controllers/concerns/session_person_creator.rb
- db/migrate/20171106164424_add_internal_auth_email_to_people.rb
- db/schema.rb
- spec/factories.rb
- spec/models/queued_notification_spec.rb
- spec/requests/person_profile_spec.rb
When authenticating against the SSO we will store the email returned by the SSO provider as the internal_auth_key. This leaves the email address as a cosmetic garnish that can be edited as desired.
> Build identity_auth_key

- app/views/people/_team_selector.html.haml
- We are not allowing users to edit teams on this page
> Remove 'add sub team' link from the edit profile page

- .env.example
- README.md
- app/controllers/sessions_controller.rb
- config/initializers/omniauth.rb
- lib/tasks/peoplefinder/db.rake
I was trying to run our version of the People Finder on my laptop and encountered a few issues. This pull request seeks to solve them.
The changes here:
- fix an issue with running the `rake peoplefinder:db:reload` command
- adds a mock authentication strategy, which can be enabled with an environment variable
> Improvements and fixes to the dev environment

- app/assets/stylesheets/modules/_module-media.scss
- app/controllers/person_deletion_request_controller.rb
- app/mailers/person_deletion_request_mailer.rb
- app/views/people/_profile.html.haml
- app/views/person_deletion_request/_breadcrumbs.html.haml
- app/views/person_deletion_request/new.html.haml
- app/views/person_deletion_request_mailer/deletion_request.text.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/person_deletion_request_controller_spec.rb
- spec/features/person_deletion_requests_spec.rb
- spec/mailers/person_deletion_request_mailer_spec.rb
This branch allows users to request profiles to be deleted when people have left the organisation.
It adds a new form to the profile page, where users can add a note. When a request is submitted, it is sent by email to the support address defined in `SUPPORT_EMAIL` – the same address shared with the `ProblemReportMailer`.
Of note is that the email is sent immediately, rather than being queued for delivery. This is because the email notification is key to the interaction being completed, and I would prefer that this errors to the user rather than quietly fails.
> Allow users to request profile deletion

- Gemfile
- Gemfile.lock
- README.md
The Mailcatcher README advises against including it in your Gemfile, and this is what's causing our asset builds to fail.
This commit removes it from the Gemfile and adds a note to our README.
> Remove Mailcatcher from Gemfile

- .rubocop.yml
- .rubocop_todo.yml
- app/policies/person_policy.rb
- app/views/group_update_mailer/inform_subscriber.html.haml
- app/views/people/_action_links.haml
- app/views/user_update_mailer/deleted_profile_email.html.haml
- config/application.rb
- spec/controllers/people_controller_spec.rb
- spec/features/flash_spec.rb
- spec/features/person_edit_notifications_spec.rb
- spec/features/person_maintenance_spec.rb
- spec/features/regression_spec.rb
- spec/policies/person_policy_spec.rb
This branch changes the editing and deletion permissions for People Finder profiles.
It re-enables editing of profiles by any user, now that email notifications are being sent out (#51). It also restricts deletion of profiles to super admins, now that users can request profiles to be deleted (#46).
This also includes some minor content changes to email notifications, and updates tests to reflect the new permission changes.
> Update profile editing and deletion permissions

- .rubocop.yml
- app/policies/group_policy.rb
- app/views/groups/_heading_links.html.haml
- app/views/groups/_people_in_team.html.haml
- app/views/groups/_teams_in_team.html.haml
- app/views/people/_team_selector.html.haml
- config/locales/en.yml
- spec/controllers/groups_controller_spec.rb
- spec/features/analytics_spec.rb
- spec/features/group_browsing_spec.rb
- spec/features/group_maintenance_spec.rb
- spec/features/login_flow_spec.rb
- spec/features/person_membership_spec.rb
- spec/policies/group_policy_spec.rb
- spec/support/login.rb
This pull request changes the `GroupPolicy` to restrict creation, editing and deletion of groups to the super admin users. 
In addition, the views have been edited so that create and edit links are only displayed when a user has permission to perform the action.
> Restrict group modifications to super admins

- app/jobs/send_notifications_job.rb
- app/models/concerns/geckoboard_datasets.rb
- spec/jobs/send_notifications_job_spec.rb
- spec/rails_helper.rb
- spec/support/geckoboard_helper.rb
This re-introduces Geckoboard publishing of statistics on the People Finder.
The publisher tasks are now run as part of the `SendNotificationsJob`, which is triggered after a profile is updated.
This will require the correct `GECKOBOARD_API_KEY` variable to be set in the staging/prod environments on deploy. However, as this is running as a background task, it will quietly fail if the details are incorrect.
> Publish to Geckoboard when profiles are updated

- app/assets/stylesheets/modules/_module-media.scss
- app/controllers/application_controller.rb
- app/views/people/_profile.html.haml
- config/application.rb
- spec/features/suggestion_spec.rb
This hides the link to suggest changes to a user's profile, as we're not using suggestions for the MVP launch.
This was previously disabled, but re-enabled inadvertently when #53 re-enabled profile editing.
> Hide suggestions

- app/helpers/application_helper.rb
- app/models/person.rb
- app/views/people/_profile.html.haml
- app/views/search/_person.html.haml
- spec/helpers/application_helper_spec.rb
- spec/models/person_spec.rb
This changes how the primary phone number is displayed to include the country dialling code.
It adds a new method to the `Person` model to return the phone country as an instance of `ISO3166::Country`, and adds helper methods to format the phone number with the dialling code.
The phone number is displayed on both the profile page and in search results, and both are updated to include the dialling code.
> Include the dialling code with the phone number

- app/controllers/concerns/session_person_creator.rb
- spec/features/omni_auth_authentication_spec.rb
Scenario:
- Person logs in via the SSO when they 
have an existing account (created manually or
by logging in with another provider)
- The login script tries to create a new record
but the email exists, so the page blows up.
Solution:
- If a user can’t be found with an internal_auth_key
that matches the email returned by the SSO provider,
we try to do a match on the person’s email.
- If we find a record for that person, we update their
internal_auth_key so that their account gets associated
with their most recent login mechanism
Note:
- Tests could be DRY-er, but want to be explicit 
that there *might* be a difference between an existing
account that was created manually and one created by
logging in with another provider
> Merge duplicate accounts when logging in with SSO

- app/views/search/index.html.haml
- spec/features/search_filter_spec.rb
- spec/features/search_spec.rb
- spec/support/pages/search.rb
This removes the link in the search footer which currently prompts users to create a new profile.
As there is nothing else in the footer, this removes the whole footer element.
> Remove search footer

- app/controllers/groups_controller.rb
- app/views/groups/show.html.haml
- spec/features/person_maintenance_spec.rb
This disables the link to create a person from a team page.
> Remove ability to create person from a team page

- app/controllers/concerns/session_person_creator.rb
- spec/features/omni_auth_authentication_spec.rb
- spec/rails_helper.rb
- On creation from an oauth login, we need to make sure that the
internal_auth_key is populated, so that the profile record can be retrieved
by the workspace
> Ensure that the internal_auth_key is populated

- app/controllers/person_email_controller.rb
- config/locales/en.yml
- spec/controllers/person_email_controller_spec.rb
https://uktrade.atlassian.net/browse/DW-470
- This is an edge case. 
- If a person has been setup without an
internal_auth_key and a different email address than the
one returned from the SSO provider, the `namesakes` workflow
kicks in and they are prompted to select a profile.
- Here we effectively `merge` their SSO auth credentials
with this Person profile, and redirect to the profile
page, as opposed to inviting them to edit their email.
> Fixes bug: Profile not correctly setup

- app/controllers/report_controller.rb
- In order to have a threaded conversation in
Zen desk, we have to pass in the Requester’s name
and email
> Zen desk expects the Requester's name and email

- spec/mailers/previews/preview_helper.rb
- The #building column is now an array, so if
we assign a string (which we don’t for this,
preview), the page blows up
> Update mailer preview helper

- spec/rails_helper.rb
Following the recommended fix from this article
https://makandracards.com/makandra/47551-don-t-require-files-in-random-order
> Use a fixed order for imports so we are not at the whim of the filesystem.

- config/initializers/carrierwave.rb
Carrierwave requires the `config.fog_credentials` configuration
parameter to be set _before_ `config.storage`, otherwise it will fail
with a cryptic error message.
> Fix Carrierwave initializer configuration order

- spec/services/person_search_spec.rb
These specs consistently fail when the test suite is run in a certain
order (via --seed).
Attempted to try and figure out what is going on, but there seems to be
a whole lot of things going wrong with the search specs (as evidenced by
the numerous specs already marked pending). Parking this until we have
time to properly triage and evaluate all the failures.
> Mark flaky search specs as pending

- config/initializers/raven.rb
Errors from People Finder currently show up in Sentry as coming from production regardless of whether they're from dev, staging, or production. This adds an initializer that sets the Raven environment based on the `APPLICATION_ENV` environment variable added in https://github.com/uktrade/ci-pipeline-config/pull/41
> Set current Raven environment based on APPLICATION_ENV

- app/views/layouts/peoplefinder.html.haml
Currently the big "Digital Workspace" link in the People Finder header
links to the PF homepage, when it should go to Workspace.
> Update header to link to Workspace homepage

- app/services/person_search.rb
- lib/tasks/peoplefinder/db.rake
- spec/services/person_search_spec.rb
People Finder handles the special case of searching for someone's full
name in a peculiar way - not only does it assume that if you are
searching for two words (no more, no less) that constitutes a full name,
it then goes and only displays *one* search result. Sounds great in
theory, but sometimes two people have the same name!
There needs to be some proper work at some point to clean up the
`PersonSearch` code and adjust the weightings, but for now this will
produce more meaningful search results.
> Remove special handling of full name searches

- config/initializers/elasticsearch.rb
`elasticsearch` is not a hash, it's an array of hashes.
> Fix issue with `VCAP_SERVICES` Elasticsearch

- config/locales/en.yml
This is an extra field requested by the security profession.
> Add "Divisional security coordinator" to responsibilities

- app/assets/stylesheets/digital-workspace-overrides/components/_search-profile-bar.scss
- app/views/layouts/peoplefinder.html.haml
- app/views/shared/_loginout.html.haml
- app/views/widgets/_people_search.html.haml
This copies over the HAML and SCSS from Digital Workspace for the new
user info header that shows an additional line of information (profile
completeness and a more obvious link to edit)
> Implement new user info header

- .travis.yml
- Gemfile.lock
- app/models/concerns/searchable.rb
- docker-compose.yml
- Update ES gems
- Change deprecated field types
- Use ES6 in Docker Compose
> Compatibility fixes for Elasticsearch 6.0

- Gemfile
- Gemfile.lock
- config/initializers/elasticsearch.rb
ES URL and credentials are now coming through `VCAP_SERVICES` on GOV.UK
PaaS, and we are no longer using AWS ES. This means we can also remove
AWS ES request signing gems as we no longer need to communicate with ES
over the internet.
> Remove old Elasticsearch initialisation logic

- app/controllers/report_controller.rb
These were failing because this app has no `root_path` (it's `home_path`
instead).
Also updates the Zendesk report subject to be more descriptive.
> Fix issue with Zendesk problem reports

- app/controllers/concerns/session_person_creator.rb
- config/initializers/omniauth.rb
- db/migrate/20190315141829_add_ditsso_user_id_to_person.rb
- db/schema.rb
- lib/ditsso_internal.rb
- spec/controllers/concerns/shared_examples_for_session_person_creator.rb
- spec/controllers/sessions_controller_spec.rb
This is the first step towards using DIT Staff SSO's `user_id` field
instead of the user's email as the primary way of identifying a user on
login.
- Before attempting to find a user by their SSO email on login, we check
if a user exists with the SSO `user_id`. Only if that is unsuccessful
do we try to find the user by email.
- On both login and user creation, store the SSO `user_id` in a new
`ditsso_user_id` column against the People Finder user, so that all
new users (and all those who log in after this changes is deployed)
will have their SSO `user_id` associated with their profile.
The next step will be creating and running a task to populate all
existing users with `user_id`s from SSO. Once that is done, the
finding by email logic can be removed (and the rest of the login
code …
> Use DIT SSO user_id to find user on login

- app/services/auth_user_loader.rb
- lib/tasks/peoplefinder/accounts.rake
- spec/services/auth_user_loader_spec.rb
- spec/spec_helper.rb
Users logging in will now have their user ID set for them, this adds a
rake task to set the user ID for all remaining users.
> Add rake task for importing Staff SSO User IDs

- app/controllers/api/people_controller.rb
- spec/factories.rb
- spec/models/queued_notification_spec.rb
- spec/requests/person_profile_spec.rb
Currently these are requested by email (`internal_auth_key`), but we are
moving away from that in both applications and should only be using the
SSO `user_id` from now on.
> Allow requesting person details in API using SSO ID

- app/models/person.rb
- app/services/random_generator.rb
- spec/features/omni_auth_authentication_spec.rb
Every person created from this point on should have a Staff SSO user ID.
This adds a validation to ensure we don't reach an invalid state.
> Make SSO UUID mandatory on people

- app/models/person.rb
- spec/models/person_spec.rb
This should never be an issue during normal operation, but can sometimes
occur during manual data munging - this ensures that SSO user IDs are
always unique.
> Add uniqueness validation for SSO user ID

- app/controllers/sessions_controller.rb
There was an issue with a user whose record refused to save, and rather
than blowing up and notifying us about it, the save just silently
failed.
There is no longer a reason for rescuing a failed save - let it fail
and then we can deal with it.
> Ensure session creation doesn't fail silently

- app/models/person.rb
- db/migrate/20190508161402_remove_uniqueness_key_on_people_email.rb
- db/schema.rb
- spec/features/person_maintenance_spec.rb
- spec/models/person_spec.rb
Since emails are no longer used for identification purposes, and we have
situations where two people would want to use the same email address
(e.g. job shares), this removes the requirement for email addresses to
be unique both in the app and the database.
> Remove requirement for unique email addresses

- app/assets/stylesheets/digital-workspace-overrides/components/_global-header.scss
- app/views/layouts/peoplefinder.html.haml
The DIT logo in the header started being overlayed with a "GOV.UK" text
after a recent GOV.UK Frontend update. This adds the 0px font size that
is being used in the Digital Workspace frontend code to harmonise the
two apps and remove the text from users' view.
> Fix white "GOV.UK" text obscuring header logo

- app/controllers/people_controller.rb
- app/views/people/_form.html.haml
- config/initializers/carrierwave.rb
- config/locales/en.yml
- spec/controllers/people_controller_spec.rb
This can be used to correct issues with users being deleted from SSO and
recreated (with a new ID), leading to their People Finder profiles becoming
detached from their SSO identity.
- Add field in administrative section to update `ditsso_user_id`
- Fix configuration failure with blank values in env file
> Allow super admins to set SSO user ID

- app/controllers/admin/profile_extracts_controller.rb
To help with reporting, because there can be multiple teams with the
same name but in different structures, add the ID of the team in to
the profile extracts.
> Add Team ID to profile CSV extracts

- app/controllers/admin/team_extracts_controller.rb
- app/views/admin/management/show.html.haml
- config/routes.rb
- spec/features/csv_extract_spec.rb
We need to be able to run reports that correlate people to teams, and this
allows us to generate a list of teams and their structure in the same way
that we can export lists of profiles.
> Add team structure export to management area

- docker-compose.yml
People Finder uses Docker (and Docker Compose) for local development.
This improves performance (particularly on macOS) and generally
improves the local experience by:
- Setting container volumes to `delegated` (which means that rather
than guaranteeing consistency all the time, Docker will consider
the container file system as authoritative and changes may take
a split second to propagate onto the host file system, which is
perfectly fine for our use case) - this massively improves IO
performance on macOS
- Making Rails write its Pidfile to `/dev/null` (because it rarely
managed to clean up after itself properly)
> Docker performance improvements

- app/models/concerns/completion.rb
- app/models/concerns/geckoboard_datasets.rb
- app/models/person.rb
- app/uploaders/image_uploader.rb
- db/migrate/20190916141532_remove_legacy_profile_image_from_people.rb
- db/schema.rb
- lib/s3/bucket.rb
- spec/models/concerns/completion_spec.rb
- spec/models/person_spec.rb
- spec/uploaders/image_uploader_spec.rb
Long before being launched at DIT, People Finder changed how it handled
uploaded profile images (from an `image` column to a `ProfilePhoto`
model). Rather than migrating all users to the new profile images, the
code was modified to allow picking up either of the two storage
locations.
This removes all references to the legacy image storage as this was
never used at DIT.
> Remove legacy profile image upload functionality

- Gemfile
- Gemfile.lock
- app/helpers/application_helper.rb
- app/views/groups/_subgroup.html.haml
- app/views/groups/show.html.haml
- app/views/pages/show.html.haml
- spec/helpers/application_helper_spec.rb
We use the `govspeak` library to parse Markdown in People Finder - this
is complete overkill for what is a tiny subset of Markdown being used,
especially since the latest version of the library substantially
increases the number of dependencies required to the point of basically
including half of GOV.UK.
This replaces it with `kramdown`, which is much smaller and does the
same thing, and cleans up the Markdown-related code in the process.
> Remove Govspeak from app

- app/helpers/application_helper.rb
This brings the generated HTML back in line with the previous
Markdown parser.
> Extend list of allowed Markdown tags

- app/controllers/api/search_controller.rb
- config/routes.rb
Adds a trivial API endpoint returning search results, to be used in an
experimental search service.
> Add proof-of-concept search API

- app/controllers/api/search_controller.rb
- config/routes.rb
Unfortunately the existing search and API implementation doesn't give us
much to work with. Rather than re-implementing the search functionalty,
this hacks together a basic, functional search API to allow us to
validate our PoC for now.
> Improve search API proof of concept

- app/assets/stylesheets/digital-workspace-overrides/components/_edit-profile.scss
- app/assets/stylesheets/digital-workspace-overrides/components/_search-profile-bar.scss
- app/assets/stylesheets/digital-workspace-overrides/util/_links.scss
- app/assets/stylesheets/digital-workspace-overrides/util/_pf-specific-overrides.scss
- app/assets/stylesheets/digital-workspace-overrides/vars/_colours.scss
- Change profile bar to grey background
The transparent red background lets too much of the pattern beneath
through, leading to poor legibility
- Replace orange links with GOV.UK link colour/brand red
The orange link colour is neither on brand nor does it provide
decent contrast. This changes all links to current GOV.UK link blue
> Implement UX review "quick win" recommendations

- Gemfile
- Gemfile.lock
- app/controllers/api/application_controller.rb
- app/controllers/api/people_controller.rb
- app/controllers/api/v2/people_controller.rb
- app/serializers/legacy_profile_serializer.rb
- app/serializers/person_serializer.rb
- config/initializers/active_model_serializer.rb
- config/routes.rb
- spec/factories.rb
- spec/features/person_membership_spec.rb
- spec/requests/api/legacy_person_profile_spec.rb
- spec/serializers/legacy_profile_serializer_spec.rb
- spec/serializers/person_serializer_spec.rb
Change the "legacy" profile API, and add a new API for person data
- Remove use of `ActiveModel::Serializers`
We include an entire (abandoned) gem to serialise a single API
response into a JSON API style, we might as well do that
manually
- Remove unnecessary `json` gem and unused `jbuilder` gem
- Use ENV#fetch to ensure an API auth token *must* be provided
> Improve APIs

- Gemfile
- Gemfile.lock
- app/models/group.rb
- app/models/person.rb
- lib/csv_publisher/user_behavior_report.rb
- lib/geckoboard_publisher/report.rb
- spec/controllers/groups_controller_spec.rb
- spec/models/group_spec.rb
- spec/rails_helper.rb
- Remove pointless `database_cleaner` gem (this gem just replicates
Rails's built in "transactional tests" functionality, no idea why
it was ever added to this project)
- Fix convoluted root group validation and AR scope deprecation warning
- Remove unused `Person.all_in_groups_scope`
- Make `Person.all_in_subtree` class method instead of scope to fix
deprecation issues
- Use `module_parent_name` instead of `parent_name` to fix deprecation
warning
> Improve tests and fix some deprecation warnings

- Gemfile.lock
- manifest.yml
The deploy is failing due to an issue with the lastest buildpacks'
integration with Bundler 2.x. Downgrading buildpack for now.
c.f. https://github.com/cloudfoundry/ruby-buildpack/issues/120
> Downgrade CloudFoundry buildpack to 1.8.4

- spec/factories.rb
- spec/form_builders/person_form_builder_spec.rb
- The `Group(:department)` factory uses `find_or_create` on a leaky
scope, which was supported until now but will be fixed in Rails 6.1
- The `PersonFormBuilder` spec needs a (nil) lookup context to be
provided
> Fix Rails 6.1 deprecations in test suite

- .env.example
- .reek.yml
- Gemfile
- Gemfile.lock
- config/application.rb
- config/environments/production.rb
- config/initializers/elasticsearch.rb
- config/initializers/health_check.rb
- config/initializers/session_store.rb
- docker-compose.yml
- lib/vcap_services.rb
- spec/fixtures/files/vcap_services.json
- spec/lib/vcap_services_spec.rb
We're currently storing sessions in the database, which isn't our
preferred way, and isn't being cleaned up properly.
- Add Redis gem
- Clean up Elasticsearch VCAP_SERVICES config
- Add VCAP Services helper library
- Use new VCAP Services helper for Elasticsearch
- Add Redis configuration
- Update env example and docker compose
- Store sessions in cache; not DB
- Expire sessions after 1 hour
> Change session storage to Redis

- .reek.yml
- Gemfile
- Gemfile.lock
- app/jobs/update_group_members_completion_score_job.rb
- config/application.rb
- config/initializers/sidekiq.rb
- spec/jobs/update_group_members_completion_score_job_spec.rb
- Add sidekiq gem
- Configure Sidekiq to use dedicated Redis instance
- Swap ActiveJob configuration to use Sidekiq
- Remove over-the-top duplicate job checking from
`UpdateMembersCompletionScoreJob`
> Change ActiveJob to use Sidekiq

- Gemfile
- Gemfile.lock
- config/initializers/sidekiq.rb
The latest version of Sidekiq requires Redis 4.0 or higher – PaaS is
stuck on 3.x.
> Downgrade Sidekiq until GOV.UK PaaS supports Redis 4

- app/views/layouts/_header.html.slim
- app/webpacker/stylesheets/application.scss
- app/webpacker/stylesheets/components/legacy_workspace_search.scss
As we do not yet have a deployed combined search application, we need to
replicate the awful top-right-of-page separate search bar for now.
> Replicate Workspace search bar in new frontend

- Gemfile
- Gemfile.lock
This won't improve gem installation performance yet, as some legacy
dependencies still incorrectly require _all_ of Rails.
> Only specify needed Rails gems in Gemfile

- Gemfile
- Gemfile.lock
- app/presenters/audit_version_presenter.rb
- app/views/shared/_audit.html.slim
- app/views/shared/_audit_legacy.html.haml
- spec/features/person_audit_spec.rb
This doesn't really add value to users - we don't need to display the
browser a user made a change from or what their IP is. We log this stuff
anyway through other mechanisms, and we can keep it around in the DB for
now as `paper_trail` tracks it anyway, but we shouldn't show superfluous
information for the sake of it.
> Remove IP and browser info from user-facing audit trail

- .bowerrc
- bower.json
These are committed into `vendor/` anyway, which will be removed
shortly.
> Remove bower artefacts

- app/controllers/admin/management_controller.rb
- app/views/admin/management/show.html.slim
This allows administrators to more easily identify users that currently
have a given permission assigned.
> Add list of privileged users to management page

- app/interactors/login_person.rb
The move to the new `LoginPerson` interactor changed the method of saving
from `#save` to `#save!` because the operation shouldn't really fail.
However, in cases where there is an existing inconsistent record in the
DB, this _can_ fail and cause an error, so we need to catch it (and ship
it off to Sentry so we can investigate those accounts where that happens).
> Don't fail login if user record fails to save

- app/services/person_search.rb
The search code wasn't including memberships so the search results
would fetch membership records for every single result. The search
code needs to be rewritten eventually, but for now this will do.
> Fix n+1 query on search results

- app/helpers/people_helper.rb
This was showing _all_ working days instead of just the ones
a person was working.
> Fix issue with incorrect working days on profile

- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
SimpleCov is causing issues with the test suite, not to mention coverage
isn't that great to begin with, and the various byebug gems
on top of pry aren't necessary.
> Remove unused test/development dependencies

- app/interactors/login_person.rb
- config/locales/legacy.en.yml
Redirect users that are invalid to the profile edit page on login
(usually means they have no team set)
> Refactor `LoginPerson` interactor

- app/interactors/update_profile.rb
- app/services/mailchimp.rb
- app/workers/remove_person_from_mailing_list_worker.rb
- app/workers/update_person_on_mailing_list_worker.rb
- spec/interactors/update_profile_spec.rb
- spec/services/mailchimp_spec.rb
- spec/workers/remove_person_from_mailing_list_worker_spec.rb
- spec/workers/update_person_on_mailing_list_worker_spec.rb
- Archive subscribers instead of setting status to cleaned
- Add ability to set tags in Mailchimp service
- Push basic building tags into Mailchimp
- Refactor DI in workers
> Mailchimp tags MVP; archive subscribers

- app/interactors/update_person_on_mailing_list.rb
- app/interactors/update_profile.rb
- spec/interactors/update_person_on_mailing_list_spec.rb
- spec/interactors/update_profile_spec.rb
This will allow us to just call interactors in bulk for an initial
import of data, and divides responsibility a bit more cleanly.
> Refactor mailing list updates into separate interactor

- .env.example
- app/interactors/remove_person.rb
- app/interactors/update_profile.rb
- config/application.rb
- config/environments/test.rb
- spec/interactors/remove_person_spec.rb
- spec/interactors/update_profile_spec.rb
- spec/models/person_spec.rb
- spec/spec_helper.rb
People Finder integrates with a number of external systems as part of
the person management lifecycle. Some of those may offer sandbox
environments and/or no-op API keys that can be used locally or in
development, CI, and staging environments, but others don't.
This adds the ability to use an environment variable to enable/disable
integration with these systems to remove the need to set API keys and
possibly end up with test data being sent to live integrations.
> Add ability to disable external integrations

- app/policies/admin/management_policy.rb
- config/routes.rb
- lib/admin_route_constraint.rb
- spec/features/management_spec.rb
- spec/policies/admin/management_policy_spec.rb
Useful for debugging purposes and job visibility.
- Add Sidekiq Web UI
- Add `AdminRouteConstraint` to allow for route-level access control to
Sidekiq UI
> Add Sidekiq Web UI

- app/interactors/mailing_lists/bulk_sync.rb
- spec/interactors/mailing_lists/bulk_sync_spec.rb
This shouldn't run unless external integrations are enabled
> Disable bulk sync when external integrations disabled

- app/controllers/api/v2/data_workspace_exports_controller.rb
- app/serializers/data_workspace_person_serializer.rb
- config/routes.rb
- spec/serializers/data_workspace_person_serializer_spec.rb
This allows us to export the data currently included in the CSV extract
(and more) over an API instead.
> Initial Data Workspace export API endpoint

- app/decorators/mailing_list_person_decorator.rb
- app/interactors/mailing_lists/create_or_update_subscriber_for_person.rb
- spec/decorators/mailing_list_person_decorator_spec.rb
- spec/interactors/mailing_lists/create_or_update_subscriber_for_person_spec.rb
- Refactor tag/merge field logic from Mailchimp interactor into
decorator
- Add list of domains considered part of group and add tag
accordingly
> Add Mailchimp tag for "One DIT" group

- Procfile
We are seeing issues in production with Sidekiq workers being killed
frequently due to running out of memory. This attempts to tweak memory
consumption of workers as follows:
- Reduce threading (from default 25 to explicit 5)
- Set `MALLOC_ARENA_MAX` to 2 to reduce glibc memory arena count
(c.f. https://www.mikeperham.com/2018/04/25/taming-rails-memory-bloat)
> Tune Sidekiq to resolve memory management issues

- app/controllers/admin/profile_extracts_controller.rb
- app/helpers/application_helper.rb
- app/models/person.rb
- app/serializers/person_data_workspace_serializer.rb
- config/initializers/country_select.rb
- spec/helpers/application_helper_spec.rb
- spec/models/person_spec.rb
This still remained in a handful of places and can now be removed.
> Remove phone number country code handling

- app/serializers/person_profile_serializer.rb
- spec/serializers/person_profile_serializer_spec.rb
The changes in the new photo upload flow seem to have broken the profile
image API which no longer returns a URL for default images (just an
image name). This forces the API to return `nil` when the profile image
URL doesn't seem to be a URL (doesn't start with 'http') so Digital
Workspace doesn't 500 for users without profile images.
> Hotfix for empty profile image API issue

- app/controllers/people_controller.rb
- app/models/concerns/searchable.rb
- app/models/person.rb
- app/services/person_search.rb
- app/validators/email_address_validator.rb
- app/views/people/edit.html.slim
- app/views/people/show.html.slim
- app/views/search/_person.html.haml
- app/webpacker/javascript/controllers/person_additional_emails_controller.js
- app/webpacker/stylesheets/components/profile_edit.scss
- config/locales/en.yml
- db/migrate/20200821103046_add_more_emails_to_people.rb
- db/schema.rb
- spec/models/person_spec.rb
Some users do not want their colleagues to contact them on their main
official email address. This adds the ability to separately specify
an official individual email address, and an optional contact email
address, which if specified replaces the address shown on the user's
profile.
> Allow users to specify separate contact email

- app/models/search.rb
- Add apostrophe to acceptable search term characters
- Set `number_of_fragments` to 0 for highlights (avoids highlight only
returning partial names when name contains full stop character)
> Tweak search logic

- app/models/person.rb
Data Workspace experiences an intermittent issue where records are duplicated in the data it fetches from People Finder. The duplicate record is the last on one page, and the first in the next; and it looks like there are two users in People Finder with the this person's first and last names.
Before this PR, their order in the pagination is not defined, and so PostgreSQL is well with its rights to order them differently on each request. So, sometimes the same one of these two people will be on both pages.
So, we order people with the same name by their ID so it won't change between requests.
> fix: speculative fix on duplicate records on different pages in Data Workspace export

- app/models/person.rb
- config/locales/en.yml
Deployment steps:
1. deploy code
2. run the following SQL
```sql
UPDATE
people
SET
building =
CASE
WHEN array_position(building, 'home') IS NULL
THEN array_replace(building, 'victoria_50', 'home')
ELSE array_remove(building, 'victoria_50')
END
WHERE
array_position(building, 'victoria_50') IS NOT NULL;
```
This query will move all users from "Windsor House" to "Remote (home worker)".
> PFM-59 Remove "Windsor House" option from profile.
